server:
  port: 8082
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: shopping_service
  datasource:
    url: jdbc:mysql://localhost:3306/goods
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

