server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: goods_service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/goods/**
        - id: shopping_service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/cart/**
        - id: feedback_service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/feedback/**
