server:
  port: 8081
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: goods_service
  datasource:
    url: jdbc:mysql://localhost:3306/goods
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    enable:
      all: false
      jvm:
        memory: true
      http:
        server: true

    export:
      prometheus:
        enabled: true
